version: '3'

services:
  web:
    build: ./web
    ports:
      - "5000:5000"
    links:
      - db
    # https://medium.com/@zwinny/docker-using-webcam-9fafb26cf1e6
    # https://gist.github.com/enric1994/7ab05985f775cb2954de6c30b72b07f9
    devices:
      - /dev/video0:/dev/video0
      # https://blog.jessfraz.com/post/docker-containers-on-the-desktop/
      #- /dev/snd \ # so we have sound
    environment:
      - DISPLAY=unix:0 #DISPLAY=unix$DISPLAY
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
  db:
    build: ./db
